export enum EntityEnum {
  order = 'order',
  inventoryItem = 'inventory-item',
  partnerLocationInventoryItem = 'partner-location-inventory-item',
  orderItem = 'order-item',
  outboundShipment = 'outbound-shipment',
  outboundShipmentItem = 'outbound-shipment-item',
  returnShipment = 'return-shipment',
  returnShipmentItem = 'return-shipment-item',
  inventoryLevel = 'inventory-level',
  inboundNotice = 'inbound-notice',
  inboundReceipt = 'inbound-receipt',
  returnRequest = 'return-request',
  trackingRequest = 'trackingRequest',
  trackingResponse = 'trackingResponse',
  error = 'error',
  refundOrder = 'refund-order',
  partnerLocationStorageItem = 'partner-location-storage-item',
  emailSummary = 'email-summary',
  report = 'report',
  connectionAuth = 'connection-auth',
  cancelledOrder = 'cancelled-order',
  fieldMapper = 'field-mapper',
  dataMigration = 'data-migration',
  tracking = 'tracking'
}