export const ValidOrders = [
  {
    "id": 1936,
    "createdAt": "2023-02-27T13:00:22.967Z",
    "updatedAt": "2023-03-07T08:53:59.149Z",
    "implementationId": 106,
    "customerOrderId": "customerOrderId",
    "partnerOrderId": "1936",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "DHL",
    "paymentMethod": "2",
    "tags": null,
    "placedAt": "2023-02-27T12:44:42.060Z",
    "customerOrderNumber": "23232",
    "totalNet": "0.000000",
    "totalTaxAmount": "0.000000",
    "totalTaxRate": "0.000000",
    "shippingCost": "0.000000",
    "shippingCostNet": "0.000000",
    "shippingTaxAmount": "0.000000",
    "shippingTaxRate": "0.000000",
    "discount": "0.000000",
    "discountNet": "0.000000",
    "discountTaxAmount": "0.000000",
    "discountTaxRate": "0.000000",
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1273,
        "createdAt": "2023-02-27T13:00:22.967Z",
        "updatedAt": "2023-02-27T13:00:22.967Z",
        "orderId": 1936,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "1000.000000",
        "quantity": 1,
        "currency": "string",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": '200',
        "pricePaidNet": "100.000000",
        "taxAmount": "1.000000",
        "taxRate": "0.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  },
  {
    "id": 1938,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": null,
    "shippingCostNet": null,
    "shippingTaxAmount": null,
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "1000.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "100",
        "pricePaidNet": "10.000000",
        "taxAmount": "1.000000",
        "taxRate": "0.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  }
]

export const OrdersWithInvalidShippingPrice = [
  {
    "id": 1940,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": null,
    "shippingCostNet": '100.000000',
    "shippingTaxAmount": "10.000000",
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "1000.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "10.000000",
        "pricePaidNet": "100.000000",
        "taxAmount": '10.000000',
        "taxRate": "2.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  },
  {
    "id": 1941,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": null,
    "shippingCostNet": "10.000000",
    "shippingTaxAmount": null,
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "1000.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "20.000000",
        "pricePaidNet": "10.000000",
        "taxAmount": "2.000000",
        "taxRate": "0.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  }
]


export const OrdersWithInvalidPricePaidNet = [
  {
    "id": 1940,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": null,
    "shippingCostNet": '100.000000',
    "shippingTaxAmount": "10.000000",
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "0.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "10.000000",
        "pricePaidNet": "100.000000",
        "taxAmount": '10.000000',
        "taxRate": "2.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  },
  {
    "id": 1941,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": "10",
    "shippingCostNet": "1.000000",
    "shippingTaxAmount": null,
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "0.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "20.000000",
        "pricePaidNet": "10.000000",
        "taxAmount": "0.000000",
        "taxRate": "0.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  }
]


export const OrdersWithInvalidUnitPriceNet = [
  {
    "id": 1940,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": null,
    "shippingCostNet": '100.000000',
    "shippingTaxAmount": "10.000000",
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "0.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "10.000000",
        "pricePaidNet": "100.000000",
        "taxAmount": '10.000000',
        "taxRate": "2.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  },
  {
    "id": 1941,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": "10",
    "shippingCostNet": "1.000000",
    "shippingTaxAmount": null,
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "0.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "20.000000",
        "pricePaidNet": "10.000000",
        "taxAmount": "0.000000",
        "taxRate": "0.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  }
]

export const OrdersWithShippingCostNetZero = [
  {
    "id": 1940,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": 100,
    "totalTaxAmount": 100,
    "totalTaxRate": 10,
    "shippingCost": 100,
    "shippingCostNet": '100.000000',
    "shippingTaxAmount": "10.000000",
    "shippingTaxRate": 10,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "0.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "0.000000",
        "unitPriceNet": "10.000000",
        "pricePaidNet": "100.000000",
        "taxAmount": '10.000000',
        "taxRate": "2.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  },
  {
    "id": 1941,
    "createdAt": "2023-03-01T07:23:49.965Z",
    "updatedAt": "2023-03-07T08:53:54.949Z",
    "implementationId": 106,
    "customerOrderId": "string",
    "partnerOrderId": "Tm3 Test-106-1938",
    "channel": "shopify",
    "total": "1000.000000",
    "currency": "AUD",
    "shippingFirstName": "string",
    "shippingLastName": "string",
    "shippingAddressLine1": "string",
    "shippingAddressLine2": "string",
    "shippingCompanyName": "string",
    "shippingEmail": "santosh@gmail.com",
    "shippingZip": "string",
    "shippingCity": "string",
    "shippingRegion": "string",
    "shippingCountryCodeIso": "NP",
    "shippingPhone": "string",
    "shippingMethod": "string",
    "paymentMethod": "string",
    "tags": null,
    "placedAt": "2023-03-01T05:44:46.545Z",
    "customerOrderNumber": "string",
    "totalNet": null,
    "totalTaxAmount": null,
    "totalTaxRate": null,
    "shippingCost": "10",
    "shippingCostNet": "0",
    "shippingTaxAmount": null,
    "shippingTaxRate": null,
    "discount": null,
    "discountNet": null,
    "discountTaxAmount": null,
    "discountTaxRate": null,
    "billingFirstName": "string",
    "billingLastName": "string",
    "billingAddressLine1": "string",
    "billingAddressLine2": "string",
    "billingCompanyName": "string",
    "billingEmail": "santosh@gmail.com",
    "billingZip": "string",
    "billingCity": "string",
    "billingRegion": "string",
    "billingCountryCodeIso": "NP",
    "billingPhone": "string",
    "metaInfo": {},
    "currentStatus": "waiting-for-fulfillment",
    "refundStatus": null,
    "relatedOrderId": null,
    "orderItems": [
      {
        "id": 1275,
        "createdAt": "2023-03-01T07:23:49.965Z",
        "updatedAt": "2023-03-01T07:23:49.965Z",
        "orderId": 1938,
        "inventoryItemSku": "SKU1111",
        "inventoryItemSkuImplementation": "SKU1111_106",
        "pricePaid": "1.000000",
        "quantity": 1,
        "currency": "AUD",
        "customerLineItemId": "string",
        "unitPrice": "1.000000",
        "unitPriceNet": "20.000000",
        "pricePaidNet": "10.000000",
        "taxAmount": "1.000000",
        "taxRate": "1.000000",
        "isBundle": false,
        "belongsToBundle": false,
        "metaInfo": {},
        "discount": "0.000000",
        "discountNet": "0.000000",
        "discountTaxAmount": "0.000000",
        "discountTaxRate": "0.000000",
        "isShipsWithItem": false,
        "inventoryItem": {
          "id": 312,
          "createdAt": "2023-01-17T08:58:09.244Z",
          "updatedAt": "2023-01-17T08:58:09.244Z",
          "sku": "SKU1111",
          "skuImplementation": "SKU1111_106",
          "implementationId": 106,
          "customerItemId": "44189392994613",
          "partnerItemId": null,
          "dimensions": {
            "weight": 0,
            "weightUnit": "kg"
          },
          "name": "Sandwich",
          "wmsSyncedAt": null,
          "shopSyncedAt": "2023-01-17T08:58:09.151Z",
          "source": "shopify",
          "barcode": "",
          "price": "12.000000",
          "harmonizedSystemCode": null,
          "countryCodeOfOrigin": null,
          "customerItemType": null,
          "isBundle": false,
          "metaInfo": {
            "shopify_inventory_item_id": "46237106635061"
          },
          "packagingRatio": null,
          "packagingGroupSku": null,
          "notFulfillable": false,
          "noInventoryLevelUpdate": false,
          "isReady": false,
          "lowStockAt": null,
          "lowStockThreshold": null,
          "returnPeriod": null,
          "imagesUrl": [
            {
              "url": "https://cdn.shopify.com/s/files/1/0698/1615/6469/products/toast-7009956_1280.webp?v=1673255566"
            }
          ]
        }
      }
    ]
  }
]